### ISSUE TITLE
Divination window, ranged cards are launched on melees.

### ISSUE THREAD

**Issue by Nitrodroki** [aiczk/Astro#13]
Problem not solved sadly.

**Comment by aiczk** [comment]
This problem requires a change in the algorithm, which I think will take less time than the "60 second burst" option, but I'll give it a try.

**Comment by Nitrodroki** [comment]
I think it needs to be worked on as high priority, people are starting to wonder if I'm trolling by casting a ranged card on a DRK. :p

**Comment by Impurities** [comment]
Same here, it seems like it's just swapped, melee cards are going to ranged, and ranged cards are going to melee.

This happens when the "Deal three cards at burst" is selected

**Comment by aiczk** [comment]
Sorry, I went to the raid dozens of times in our environment to check and that phenomenon did not occur.
I implemented the debug option in ver 1.25, so please send me the logs.
I hope you will be able to provide the information.

**Comment by Nitrodroki** [comment]
So, it's still not working. 

Some footage for example, its a bit blurry but you'll see that a spire is launched on RPR while none of the range have a card already, and its pretty systematic but only for the divination window.

https://youtube.com/clip/Ugkxut3vYs45qoWpvMUXmLWUWqPBtyYQGwMt

Another one with range card on DRK

https://youtube.com/clip/UgkxjBO5nc9VVgsM9bQKOHoJs7irakcsnN6I

You can look through the vod if you want for more.

For context I only use manual targetting since all other options have been bugged or slip ogcds that i dont want to interfere even the manual ones. :s

It is only ranged -> Melee tho, I don't believe i've seen melee cards put on ranges so I think its a problem with specifically the divination window and ranged cards.

I hope it helped

**Comment by abranon** [comment]
If it's dropping information in logs you should provide them at this point, I've used this on two different setups and haven't run into this issue myself so it might be a conflicting mod on your end but the mod devs won't know without logs. 

But also to the mod developers, the live letter mentioned an Astro rework, I believe we're waiting on substantial information. Just wanted to drop this heads-up to save some headache in case y'all were planning big mod changes :)

**Comment by Impurities** [comment]
I tried with the debug message, it seems that the video is proof enough, the debug message simply outputs to your chat log if the card is Melee and to who it is being given to, which as you can see in the video, is erroneously identifying "The Spire" as a Melee card, and giving it to the Reaper, when "The Spire" is a ranged card.

It behaves normally if divination window is disabled, however, and correctly identifies and distributes cards.

There are no logs in the Dalamud.log for Astro.

**Comment by aiczk** [comment]
Sorry for not being able to reply.
Please give me a little more time as I have been investigating the cause for a long time but am not quite sure what it is.
As for the issue of no output in the Log, it will be resolved in the ver 1.26 update.
Also, please forgive the large amount of logs being generated, as this is due to the use of FF14's specifications.

**Comment by Impurities** [comment]
Here is my latest log, ranged cards are being identified as "random", and even distributing cards to healers. It does not have this behavior when using manual play, with auto play/divination window disabled.
[dalamud.log](https://github.com/aiczk/Astro/files/9034110/dalamud.log)

**Comment by aiczk** [comment]
Thanks for the log.
I'm starting to understand the cause of the problem, the target sorting algorithm is doing something bad, and if I can just fix this, I think the problem will be solved.
I will do my best to fix it.

**Comment by aiczk** [comment]
Fixed a bug in ver 1.27 that distributed cards to random players.
I have tested and checked the logs and it seems to be working correctly.
I apologize for any inconvenience this may have caused.

**Comment by Nitrodroki** [comment]
From what I tested it worked very well, but the crashes made the test session shorter than I would like to close the issue yet. :)
